"""add language to posts

Revision ID: 868840ae5e84
Revises: 3a5be69e4f4a
Create Date: 2020-08-17 15:41:04.677539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868840ae5e84'
down_revision = '3a5be69e4f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
